# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jake LeBoeuf 
email: dev@jakeleboeuf.com
description: > # this means to ignore newlines until "baseurl:"
  Thanks for reading :)  
baseurl: "/about" # the subpath of your site, e.g. /blog
url: "http://jakeleboeuf.github.io" # the base hostname & protocol for your site
twitter_username: jakeleboeuf
github_username:  jakeleboeuf

# Build settings
markdown: kramdown

# Use smart things
gems:
  - octopress-autoprefixer

# Don't do things to build files
exclude: [package.json, node_modules, gulpfile.js]
